### ISSUE TITLE
create new npm package cubx-webpackage-downloader

### ISSUE THREAD

**Issue by pwrinc** [cubbles/cubbles#13]
**Solution approach:**
1. Get `manifest.webpackage` document for each of the given webpackages and resolve it's resources by requesting each seperately from base (Note: use parallel request for getting resources)
1. Allways download complete webpackages
1. Povide a CLI:
* `-o`: local target directory for downloaded webpackage
* `-w`: list of webpackages to be requested. Can be:
  * Comma-separated list of webpackages 
  * a reference to a .json file with a list of webpackages
  * inline JSON list of webpackages
* `-b`: base URL to use

**Comment by hrbu** [comment]
Using promises with async and await: https://blog.risingstack.com/mastering-async-await-in-nodejs/

**Comment by edwingamboa** [comment]
The module can be tested under the develop branch.

#### Examples of use:

- cubx-webpackage-downloader **-o** test/resources/download **-w** '["com.incowia.ajax@0.2.6", "com.incowia.cubx-webpackage-viewer@1.7.0"]' **-b** https://cubbles.world/sandbox
- cubx-webpackage-downloader **-o** test/resources/download **-w** 'com.incowia.ajax@0.2.6,com.incowia.cubx-webpackage-viewer@1.7.0' **-b** https://cubbles.world/sandbox
- cubx-webpackage-downloader **-o** test/resources/download **-w** path/to/a/json/file.json **-b** https://cubbles.world/sandbox

**Comment by pwrinc** [comment]
@edwingamboa: I tried to use the webpackage downloader but got the following error (please see screenshot). Seems like my provided target path was not working. Although I just created a folder `downloads` which I wanted to use. (see `ls` output in screenshot below)

![cubbles-cubbles 13](https://user-images.githubusercontent.com/16875399/43324264-fbd32fc2-91b3-11e8-80f0-5554ee87bf25.PNG)

**Comment by edwingamboa** [comment]
@pwrinc you can test it now

**Comment by pwrinc** [comment]
@edwingamboa. Just tested, looks good. Please publish to npm
