### ISSUE TITLE
Create open data map visualization demo using RTE 3

### ISSUE THREAD

**Issue by pwrinc** [cubbles/cubbles#16]
For demonstration and testing purposes a new cubbles demo should be created using the RTE 3.0.

**Scenario:**
Provide a cubbles component (this will be a compound component) wich show all kindergardens in the city of Potsdam. The data is provided by the open data portal of the city available under https://opendata.potsdam.de/explore/?sort=modified. The component should fetch data from REST API endpoint https://opendata.potsdam.de/api/records/1.0/search/?dataset=kitaboerse-20161108&rows=140 and display each kindergarden in the map using a marker. When clicking that marker there should be a short info popping up showing the name and the contact data (phone number) of the associated kindergarden.

**Solution approach:**
1. Migrate existing component for ajax request do use RTE 3.0
1. Migrate existing component for google map to use RTE 3.0 (**OR** according to the google map license and the usage restrictions it might be better to create a new maps cubbles component using open street map)
1. To get geocoords of each kindergarden out of the given address use the api https://www.programmableweb.com/api/mapquest-geocoding
1. Create new repository in iCubbles organistaion on github

**Comment by edwingamboa** [comment]
Google Maps is not free anymore. Developers can use with an API key, depending on the use it can be free, but a valid billing method should be provided (See  https://stackoverflow.com/a/50207868/8082984).

Thus, OpenStreetMap should be used. In this context, leaflet seems to be an appropriate library for general purposes markers, popups, routes, svg areas, etc. (https://leafletjs.com/examples.html).
