### ISSUE TITLE
Add documentation about the proper use of vanilla boilerplate

### ISSUE THREAD

**Issue by edwingamboa** [cubbles/cubbles#30]

**Comment by pwrinc** [comment]
@edwingamboa: Can you adjust section https://app.gitbook.com/@cubbles/s/docs/v/coder-template-doc/developing-vanilla-boilerplate/available-scripts#uploading-a-webpackage-to-a-cubbles-base describing how to setup the cubbles base upload config? Currently the uploader configs don't reside in their own files. Instead they are now part of the `package.json`

**Comment by edwingamboa** [comment]
Two sites were updated: 

- https://cubbles.gitbook.io/docs/v/coder-template-doc/developing-vanilla-boilerplate/creating-project#the-package-json-file
- https://cubbles.gitbook.io/docs/v/coder-template-doc/developing-vanilla-boilerplate/creating-project#the-package-json-file
