### ISSUE TITLE
Create Vanilla boilerplate in cubblesMasters organization

### ISSUE THREAD

**Issue by pwrinc** [cubbles/cubbles#31]
use the content from coder-template repo and create new `vanilla` boilerplate repo in organization https://github.com/cubblesmasters

**Comment by edwingamboa** [comment]
- A [vanilla repo](https://github.com/cubblesmasters/vanilla) was created in cubblesmasters org
- The coder-template repo was removed from cubbles org
- The coder-template was renamed to vanilla-boilerplate in coder-toolset
