### ISSUE TITLE
CubblesInjector - chrome plugin

### ISSUE THREAD

**Issue by hrbu** [cubbles/cubbles#33]
## AsIs
To show Cubbles components in action, we currently need to prepare a website by including
1. the RTE scripts to be loaded
1. the component(s) to be rendered via the tag-api

## ToBe
Web developers should be enabled to inject the RTE scripts and a number of components into any existing website. This allows one to demonstrate or test a component within a real world context.

Web developers should be enabled to do so by using a dedicated Chrome extension, that is  (like the [cubbles-webinspector](https://chrome.google.com/webstore/detail/cubbles-webinspector/akfjllhjfdmmemabkfcejldemhimifhe?hl=de)) available via the chrome webstore.

### Acceptance Criterias
- [x] Name of the extension: "cubbles-injector" | CubblesInjector
- [x] Script Injection: The extension allows to define 1..n scripts to be loaded.
   * Default: The scripts loading the current version of the RTE
- [x] Snippets Injection: The extension allows 1..n components to be injected.
   * For each component, to following configurations can be made
     * snippet: HTML code of the snippet (Using Cubbles tag-api for components).
     * location: The css selector to describe the location the html-snippet should be injected on.
- [x] use a custom event for data-cubx-startevent
- [x] cubx.CRCInit config property is defined based on injected components
- [x] Auto Reload: Changing the Injector Configuration reloads the page automatically.
- [x] Configuration Save&Load: The extension allows to save the current configuration within the browsers storage.
- [x] Export & Import: The extension allows to export and import a current configuration using a json file.
- [x] Reset editor after adding a component/script
- [x] Allow using current selected element in editor
- [x] Reset all config
- [x] Edit added scripts, components
- [x] Cancel button to editor

**Comment by hrbu** [comment]
@edwingamboa , @pwrinc , @jtrs : What do you think about it?
* Is this useful?
* Am I missing something?

**Comment by edwingamboa** [comment]
I think is pretty useful. By the moment, I don't see another required feature

**Comment by jtrs** [comment]
useful...
I think by default we need the rte AND the polyfill scripts, because no no html import in chrome after march update....

**Comment by pwrinc** [comment]
By using a custom event for `data-cubx-startevent` (https://github.com/cubbles/cubx.core.rte/blob/develop/webpackages/cubx.core.rte/README.md#data-cubx-startevent-default--domcontentloaded) it should be possible to delay RTE dependency resolution until components are injected by the plugin.

Maybe we additionally need to capability to define the `cubx.CRCInit` config property via the plugin (?)

**Comment by edwingamboa** [comment]
The extension is already available in Chrome Webstore: https://chrome.google.com/webstore/detail/cubbles-injector/afgfoljcmnidfojlnnoipbneldhjnlfo
